# Quantitative Value Strategy
"Value investing" means investing in the stocks that are cheapest relative to common measures of business value (like earnings or assets).

For this project, we're going to build an investing strategy that selects the 50 stocks with the best value metrics. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.

## Library Imports
The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [2]:
import numpy as np
import pandas as pd
import math
from scipy import stats
import requests

## Importing Our List of Stocks & API Token
As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the .csv file is still in your working directory and import it with the following command:

In [59]:
stocks_stats = pd.read_csv("stocks_stats.csv")
stocks_stats_without_NaN = stocks_stats;

In [60]:
stocks_stats_without_NaN = stocks_stats_without_NaN[stocks_stats_without_NaN['P/E'].isna() == False]
stocks_stats_without_NaN = stocks_stats_without_NaN[stocks_stats_without_NaN['P/S'].isna() == False]
stocks_stats_without_NaN = stocks_stats_without_NaN[stocks_stats_without_NaN['P/B'].isna() == False]
stocks_stats_without_NaN = stocks_stats_without_NaN[stocks_stats_without_NaN['EV/EBITDA'].isna() == False]
stocks_stats_without_NaN = stocks_stats_without_NaN[stocks_stats_without_NaN['EV/Revenue'].isna() == False]
stocks_stats_without_NaN

,Symbol,Name,Price,Volume,P/E,PE Percentile,P/B,PB Percentile,P/S,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/Revenue,EV/Revenue Percentile,RV Score
0,A,Agilent Technologies Inc. Common Stock,140.210,674929,30.97,NaN,7.25,NaN,5.92,NaN,21.36,NaN,6.12,NaN,NaN
5,AAN,Aarons Holdings Company Inc. Common Stock,12.700,349004,26.20,NaN,0.62,NaN,0.21,NaN,1.91,NaN,0.56,NaN,NaN
7,AAON,AAON Inc. Common Stock,90.285,78945,65.19,NaN,8.28,NaN,5.70,NaN,30.20,NaN,5.55,NaN,NaN
8,AAP,Advance Auto Parts Inc.,137.650,480281,16.79,NaN,3.07,NaN,0.76,NaN,11.80,NaN,1.04,NaN,NaN
9,AAPL,Apple Inc. Common Stock,144.485,19134996,25.03,NaN,41.11,NaN,6.16,NaN,18.68,NaN,6.17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3715,ZM,Zoom Video Communications Inc. Class A Common ...,69.350,1758193,204.76,NaN,3.28,NaN,4.82,NaN,45.80,NaN,3.42,NaN,NaN
3718,ZTO,ZTO Express (Cayman) Inc. American Depositary ...,24.005,7674522,21.36,NaN,2.63,NaN,3.95,NaN,2.44,NaN,0.56,NaN,NaN
3720,ZTS,Zoetis Inc. Class A Common Stock,168.160,318989,37.32,NaN,17.63,NaN,9.76,NaN,24.58,NaN,10.17,NaN,NaN
3721,ZUMZ,Zumiez Inc. Common Stock,23.230,81291,10.85,NaN,1.19,NaN,0.46,NaN,6.35,NaN,0.55,NaN,NaN
3726,ZYXI,Zynex Inc. Common Stock,12.600,73928,27.28,NaN,7.57,NaN,3.39,NaN,18.29,NaN,3.33,NaN,NaN

In [115]:
stocks_less_15 = stocks_stats_without_NaN[stocks_stats_without_NaN['Price'] <= 15]
stocks_less_10 = stocks_stats_without_NaN[stocks_stats_without_NaN['Price'] <= 10]

stocks_greater_10 = stocks_stats_without_NaN[stocks_stats_without_NaN['Price'] >= 10 and
                                            stocks_stats_without_NaN['Price'] <= 30]

stocks_less_5 = stocks_stats_without_NaN[stocks_stats_without_NaN['Price'] <= 5]
stocks_less_3 = stocks_stats_without_NaN[stocks_stats_without_NaN['Price'] <= 3]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [113]:
stocks_greater_10

,Symbol,Name,Price,Volume,P/E,PE Percentile,P/B,PB Percentile,P/S,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/Revenue,EV/Revenue Percentile,RV Score
0,A,Agilent Technologies Inc. Common Stock,140.210,674929,30.97,NaN,7.25,NaN,5.92,NaN,21.36,NaN,6.12,NaN,NaN
5,AAN,Aarons Holdings Company Inc. Common Stock,12.700,349004,26.20,NaN,0.62,NaN,0.21,NaN,1.91,NaN,0.56,NaN,NaN
7,AAON,AAON Inc. Common Stock,90.285,78945,65.19,NaN,8.28,NaN,5.70,NaN,30.20,NaN,5.55,NaN,NaN
8,AAP,Advance Auto Parts Inc.,137.650,480281,16.79,NaN,3.07,NaN,0.76,NaN,11.80,NaN,1.04,NaN,NaN
9,AAPL,Apple Inc. Common Stock,144.485,19134996,25.03,NaN,41.11,NaN,6.16,NaN,18.68,NaN,6.17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3715,ZM,Zoom Video Communications Inc. Class A Common ...,69.350,1758193,204.76,NaN,3.28,NaN,4.82,NaN,45.80,NaN,3.42,NaN,NaN
3718,ZTO,ZTO Express (Cayman) Inc. American Depositary ...,24.005,7674522,21.36,NaN,2.63,NaN,3.95,NaN,2.44,NaN,0.56,NaN,NaN
3720,ZTS,Zoetis Inc. Class A Common Stock,168.160,318989,37.32,NaN,17.63,NaN,9.76,NaN,24.58,NaN,10.17,NaN,NaN
3721,ZUMZ,Zumiez Inc. Common Stock,23.230,81291,10.85,NaN,1.19,NaN,0.46,NaN,6.35,NaN,0.55,NaN,NaN
3726,ZYXI,Zynex Inc. Common Stock,12.600,73928,27.28,NaN,7.57,NaN,3.39,NaN,18.29,NaN,3.33,NaN,NaN

## Calculating Value Percentiles

We now need to calculate value score percentiles for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* EV/EBITDA
* EV/GP

Here's how we'll do this:

In [103]:
rv_dataframe = stocks_stats_without_NaN
rv_dataframe = rv_dataframe.reset_index().drop(columns='index')
metrics = {
    'P/E':'PE Percentile',
    'P/B':'PB Percentile',
    'P/S':'PS Percentile',
    'EV/EBITDA':'EV/EBITDA Percentile',
    'EV/Revenue':'EV/Revenue Percentile'
}
for metric in metrics.keys():
    for row in rv_dataframe.index:
        rv_dataframe.loc[row, metrics[metric]] \
            = stats.percentileofscore(rv_dataframe[metric], rv_dataframe.loc[row, metric])
        
rv_dataframe

,Symbol,Name,Price,Volume,P/E,PE Percentile,P/B,PB Percentile,P/S,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/Revenue,EV/Revenue Percentile,RV Score
0,A,Agilent Technologies Inc. Common Stock,140.210,674929,30.97,72.884097,7.25,87.412399,5.92,87.493261,21.36,87.008086,6.12,85.902965,NaN
1,AAN,Aarons Holdings Company Inc. Common Stock,12.700,349004,26.20,65.929919,0.62,5.768194,0.21,4.016173,1.91,10.458221,0.56,15.256065,NaN
2,AAON,AAON Inc. Common Stock,90.285,78945,65.19,90.134771,8.28,89.326146,5.70,86.846361,30.20,93.746631,5.55,83.450135,NaN
3,AAP,Advance Auto Parts Inc.,137.650,480281,16.79,44.150943,3.07,63.584906,0.76,25.849057,11.80,57.681941,1.04,30.970350,NaN
4,AAPL,Apple Inc. Common Stock,144.485,19134996,25.03,63.773585,41.11,98.706199,6.16,88.301887,18.68,81.617251,6.17,86.145553,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1850,ZM,Zoom Video Communications Inc. Class A Common ...,69.350,1758193,204.76,97.466307,3.28,66.576819,4.82,83.477089,45.80,97.142857,3.42,70.000000,NaN
1851,ZTO,ZTO Express (Cayman) Inc. American Depositary ...,24.005,7674522,21.36,56.442049,2.63,56.495957,3.95,78.921833,2.44,12.048518,0.56,15.256065,NaN
1852,ZTS,Zoetis Inc. Class A Common Stock,168.160,318989,37.32,78.733154,17.63,96.307278,9.76,94.555256,24.58,90.296496,10.17,93.315364,NaN
1853,ZUMZ,Zumiez Inc. Common Stock,23.230,81291,10.85,27.708895,1.19,20.134771,0.46,14.312668,6.35,28.409704,0.55,14.770889,NaN
1854,ZYXI,Zynex Inc. Common Stock,12.600,73928,27.28,67.897574,7.57,88.221024,3.39,74.204852,18.29,80.646900,3.33,69.002695,NaN

## Calculating the RV Score
We'll now calculate our RV Score (which stands for Robust Value), which is the value score that we'll use to filter for stocks in this investing strategy.

The RV Score will be the arithmetic mean of the 4 percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the mean function from Python's built-in statistics module.

In [104]:
from statistics import mean

for row in rv_dataframe.index:
    value_percentiles = []
    for metric in metrics.keys():
        value_percentiles.append(rv_dataframe.loc[row, metrics[metric]])
    rv_dataframe.loc[row, 'RV Score'] = mean(value_percentiles)
rv_dataframe

,Symbol,Name,Price,Volume,P/E,PE Percentile,P/B,PB Percentile,P/S,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/Revenue,EV/Revenue Percentile,RV Score
0,A,Agilent Technologies Inc. Common Stock,140.210,674929,30.97,72.884097,7.25,87.412399,5.92,87.493261,21.36,87.008086,6.12,85.902965,84.140162
1,AAN,Aarons Holdings Company Inc. Common Stock,12.700,349004,26.20,65.929919,0.62,5.768194,0.21,4.016173,1.91,10.458221,0.56,15.256065,20.285714
2,AAON,AAON Inc. Common Stock,90.285,78945,65.19,90.134771,8.28,89.326146,5.70,86.846361,30.20,93.746631,5.55,83.450135,88.700809
3,AAP,Advance Auto Parts Inc.,137.650,480281,16.79,44.150943,3.07,63.584906,0.76,25.849057,11.80,57.681941,1.04,30.970350,44.447439
4,AAPL,Apple Inc. Common Stock,144.485,19134996,25.03,63.773585,41.11,98.706199,6.16,88.301887,18.68,81.617251,6.17,86.145553,83.708895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1850,ZM,Zoom Video Communications Inc. Class A Common ...,69.350,1758193,204.76,97.466307,3.28,66.576819,4.82,83.477089,45.80,97.142857,3.42,70.000000,82.932615
1851,ZTO,ZTO Express (Cayman) Inc. American Depositary ...,24.005,7674522,21.36,56.442049,2.63,56.495957,3.95,78.921833,2.44,12.048518,0.56,15.256065,43.832884
1852,ZTS,Zoetis Inc. Class A Common Stock,168.160,318989,37.32,78.733154,17.63,96.307278,9.76,94.555256,24.58,90.296496,10.17,93.315364,90.641509
1853,ZUMZ,Zumiez Inc. Common Stock,23.230,81291,10.85,27.708895,1.19,20.134771,0.46,14.312668,6.35,28.409704,0.55,14.770889,21.067385
1854,ZYXI,Zynex Inc. Common Stock,12.600,73928,27.28,67.897574,7.57,88.221024,3.39,74.204852,18.29,80.646900,3.33,69.002695,75.994609

## Selecting the 50 Best Value StocksÂ¶

As before, we can identify the 50 best value stocks in our universe by sorting the DataFrame on the RV Score column and dropping all but the top 50 entries.

In [107]:
rv_dataframe.sort_values('RV Score', ascending=True, inplace=True)
rv_dataframe.reset_index(inplace=True, drop=True)
rv_dataframe = rv_dataframe[:50]
rv_dataframe = rv_dataframe[rv_dataframe['Volume'] > 100000]

<ipython-input-107-32b6fb3f5bf7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rv_dataframe.sort_values('RV Score', ascending=True, inplace=True)

In [108]:
rv_dataframe

,Symbol,Name,Price,Volume,P/E,PE Percentile,P/B,PB Percentile,P/S,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/Revenue,EV/Revenue Percentile,RV Score
2,IMPP,Imperial Petroleum Inc. Common Shares,0.1901,3431181,1.05,1.563342,0.14,0.458221,0.26,5.687332,-0.24,4.905660,-0.11,1.024259,2.727763
3,INPX,Inpixon Common Stock,0.9233,1898400,0.08,0.161725,0.48,3.342318,0.12,1.428571,0.90,8.355795,-2.05,0.592992,2.776280
4,JXN,Jackson Financial Inc. Class A Common Stock,41.5900,632419,0.55,0.754717,0.39,2.291105,0.24,5.094340,-2.17,3.396226,0.16,4.878706,3.283019
5,DXYN,Dixie Group Inc. (The) Common Stock,0.8802,156957,3.12,5.229111,0.29,1.185984,0.04,0.296496,-15.91,1.617251,0.40,9.811321,3.628032
12,KT,KT Corporation Common Stock,11.5650,277645,5.12,11.051213,0.49,3.665768,0.28,6.495957,0.00,5.202156,0.00,1.536388,5.590296
18,YPF,YPF Sociedad Anonima Common Stock,11.8600,1083175,3.97,7.412399,0.64,6.010782,0.47,14.824798,0.01,5.444744,0.00,1.536388,7.045822
21,PBF,PBF Energy Inc. Class A Common Stock,46.7100,670916,2.05,3.072776,1.23,21.752022,0.13,1.725067,1.50,9.326146,0.14,4.501348,8.075472
23,AULT,Ault Alliance Inc. Common Stock,0.1161,1746990,0.09,0.215633,0.14,0.458221,0.20,3.719677,-3.34,2.964960,1.15,34.204852,8.312668
26,X,United States Steel Corporation Common Stock,30.8800,2312382,3.34,5.768194,0.68,6.657682,0.40,11.725067,1.80,10.107817,0.36,8.867925,8.625337
27,HMC,Honda Motor Company Ltd. Common Stock,25.9050,294165,8.60,21.266846,0.54,4.501348,0.37,10.512129,0.04,5.741240,0.00,1.536388,8.711590
28,E,ENI S.p.A. Common Stock,28.3427,258221,2.84,4.474394,0.78,9.164420,0.37,10.512129,1.41,9.164420,0.46,11.509434,8.964960
29,GGB,Gerdau S.A. Common Stock,5.6450,3500056,3.70,6.927224,1.04,16.172507,0.45,13.908356,0.47,7.061995,0.12,4.097035,9.633423
33,PSHG,Performance Shipping Inc. Common Shares,1.0250,1521760,0.38,0.431267,0.03,0.107817,0.10,1.105121,2.31,11.266846,1.24,36.145553,9.811321
38,DINO,HF Sinclair Corporation Common Stock,51.7000,835476,3.61,6.603774,1.09,17.574124,0.27,6.064690,2.53,12.560647,0.32,7.870620,10.134771
39,ASTL,Algoma Steel Group Inc. Common Shares,8.1750,553294,4.21,8.032345,0.79,9.433962,0.58,19.703504,0.91,8.409704,0.25,6.442049,10.404313
40,SSL,Sasol Ltd. American Depositary Shares,14.8700,173552,4.36,8.463612,0.91,13.450135,0.62,20.943396,0.18,6.576819,0.05,2.938005,10.474394
42,QD,Qudian Inc. American Depositary Shares each re...,1.1300,281419,3.49,6.253369,0.17,0.592992,1.27,41.805930,-1.10,4.043127,-0.59,0.862534,10.711590
45,MBC,MasterBrand Inc. Common Stock,9.9000,274155,7.07,16.927224,0.46,3.018868,0.38,10.943396,3.46,15.256065,0.36,8.867925,11.002695
46,TX,Ternium S.A. Ternium S.A. American Depositary ...,44.4901,104218,4.90,10.323450,0.73,7.870620,0.53,17.331536,1.92,10.512129,0.39,9.541779,11.115903
47,CBAT,CBAK Energy Technology Inc. Common Stock,0.9521,204650,9.18,23.045822,0.74,8.221024,0.41,12.237197,-197.87,0.323450,0.48,12.075472,11.180593
48,ALTO,Alto Ingredients Inc. Common Stock,2.9200,282910,8.39,20.835580,0.68,6.657682,0.16,2.668464,4.67,21.078167,0.18,5.121294,11.272237

## Calculating the Number of Shares to Buy
We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a for loop to calculate the number of shares to buy for each stock in our investment universe.

In [ ]:
portfolio_input()

In [ ]:
position_size = float(portfolio_size)/len(rv_dataframe.index)
position_size
for row in rv_dataframe.index:
    rv_dataframe.loc[row, 'Number of Shares to Buy'] = math.floor(position_size/rv_dataframe.loc[row, 'Price'])
rv_dataframe.sort_values('Price')

In [ ]:
rv_dataframe

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

## Creating the Formats We'll Need For Our .xlsx File
You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase
* Float formats with 1 decimal for each valuation metric

Since we already built some formats in past sections of this course, I've included them below for you. Run this code cell before proceeding.

## Saving Our Excel Output
As before, saving our Excel output is very easy: