# Quantitative Value Strategy
"Value investing" means investing in the stocks that are cheapest relative to common measures of business value (like earnings or assets).

For this project, we're going to build an investing strategy that selects the 50 stocks with the best value metrics. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.

## Library Imports
The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [5]:
import numpy as np
import pandas as pd
import math
from scipy import stats
import requests

## Importing Our List of Stocks & API Token
As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the .csv file is still in your working directory and import it with the following command:

In [6]:
stocks = pd.read_csv('sp_500_stocks.csv')
from secrets import IEX_CLOUD_API_TOKEN

## Making Our First API Call
It's now time to make the first version of our value screener!

We'll start by building a simple value screener that ranks securities based on a single metric (the price-to-earnings ratio).

In [17]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/quote/?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()

## Parsing Our API Call
This API call has the metric we need - the price-to-earnings ratio.

Here is an example of how to parse the metric from our API call:

In [19]:
peRatio = data['peRatio']
price = data['latestPrice']
data

{'avgTotalVolume': 107662382,
 'calculationPrice': 'close',
 'change': 0.34,
 'changePercent': 0.00247,
 'close': 142.48,
 'closeSource': 'ifocaifl',
 'closeTime': 1688694924004,
 'companyName': 'Apple Inc',
 'currency': 'USD',
 'delayedPrice': 141.88,
 'delayedPriceTime': 1736038215750,
 'extendedChange': 0.33,
 'extendedChangePercent': 0.00231,
 'extendedPrice': 142.5,
 'extendedPriceTime': 1687745906265,
 'high': 146.36,
 'highSource': 'cep ityidme5eunlar1de  ',
 'highTime': 1712249441294,
 'iexAskPrice': 0,
 'iexAskSize': 0,
 'iexBidPrice': 0,
 'iexBidSize': 0,
 'iexClose': 141.186,
 'iexCloseTime': 1700936771268,
 'iexLastUpdated': 1731172679518,
 'iexMarketPercent': 0.01819684993158407,
 'iexOpen': 144.37,
 'iexOpenTime': 1678967688827,
 'iexRealtimePrice': 142.45,
 'iexRealtimeSize': 105,
 'iexVolume': 1394613,
 'lastTradeTime': 1725626072783,
 'latestPrice': 141.26,
 'latestSource': 'Close',
 'latestTime': 'October 10, 2022',
 'latestUpdate': 1688912472538,
 'latestVolume': 78453227,
 'low': 138.973,
 'lowSource': 't ereidd1i cal pm5eeuyn',
 'lowTime': 1746230051897,
 'marketCap': 2319623093456,
 'oddLotDelayedPrice': 144.122,
 'oddLotDelayedPriceTime': 1677053423569,
 'open': 143.74,
 'openTime': 1726011490232,
 'openSource': 'ifalcofi',
 'peRatio': 24.2,
 'previousClose': 141.68,
 'previousVolume': 87275964,
 'primaryExchange': 'SDAQNA',
 'symbol': 'AAPL',
 'volume': 76819894,
 'week52High': 189.64,
 'week52Low': 132.33,
 'ytdChange': -0.21202252662779827,
 'isUSMarketOpen': False}

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called chunks that we can use to divide our list of securities into groups of 100.

In [3]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'Price-to-Earnings Ratio', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [37]:
final_dataframe = pd.DataFrame(columns = my_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=quote&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        if(symbol in data and data[symbol]['quote']['peRatio'] != None and data[symbol]['quote']['latestPrice'] != None):
            final_dataframe = final_dataframe.append(
                pd.Series(
                    [
                        symbol,
                        data[symbol]['quote']['latestPrice'],
                        data[symbol]['quote']['peRatio'],
                        'N/A',
                    ], index = my_columns
                ), ignore_index=True
            )
final_dataframe

    Ticker   Price  Price-to-Earnings Ratio Number of Shares to Buy
0        A  130.29                    29.87                     N/A
1      AAL   12.46                    -4.24                     N/A
2      AAP  173.79                    19.47                     N/A
3     AAPL  141.58                    24.18                     N/A
4     ABBV  142.21                    20.04                     N/A
..     ...     ...                      ...                     ...
486    YUM  108.77                    21.86                     N/A
487    ZBH  107.03                   103.02                     N/A
488   ZBRA  263.70                    28.46                     N/A
489   ZION   50.40                     5.84                     N/A
490    ZTS  147.38                    33.42                     N/A

[491 rows x 4 columns]

## Removing Glamour Stocks

The opposite of a "value stock" is a "glamour stock". 

Since the goal of this strategy is to identify the 50 best value stocks from our universe, our next step is to remove glamour stocks from the DataFrame.

We'll sort the DataFrame by the stocks' price-to-earnings ratio, and drop all stocks outside the top 50.

In [41]:
final_dataframe.sort_values('Price-to-Earnings Ratio', ascending=True, inplace=True)
final_dataframe = final_dataframe[final_dataframe['Price-to-Earnings Ratio'] > 0]
final_dataframe = final_dataframe[:50]
final_dataframe.reset_index(inplace=True, drop=True)
final_dataframe

   Ticker   Price  Price-to-Earnings Ratio Number of Shares to Buy
0     NRG   41.50                     2.98                     N/A
1     AIG   49.89                     3.33                     N/A
2     PVH   47.50                     3.59                     N/A
3     NUE  121.57                     3.71                     N/A
4       F   11.65                     4.05                     N/A
5     COF   96.24                     4.07                     N/A
6     HPE   12.30                     4.40                     N/A
7    DISH   14.43                     4.43                     N/A
8     HPQ   26.13                     4.44                     N/A
9     PHM   40.95                     4.46                     N/A
10    AIV    7.20                     4.50                     N/A
11    SYF   31.23                     4.58                     N/A
12    MGM   32.85                     4.68                     N/A
13    PFG   76.59                     4.75                     N/A
14    DHI   73.79                     4.82                     N/A
15    APA   42.26                     4.94                     N/A
16    LYB   81.03                     4.99                     N/A
17    DOW   46.85                     5.00                     N/A
18    LEN   80.77                     5.18                     N/A
19     CE   95.36                     5.23                     N/A
20    WBA   33.24                     5.33                     N/A
21   INTC   26.00                     5.43                     N/A
22    KSS   27.66                     5.43                     N/A
23      C   43.30                     5.44                     N/A
24      T   15.20                     5.61                     N/A
25   ZION   50.40                     5.84                     N/A
26    TSN   66.70                     6.00                     N/A
27    DFS   94.63                     6.02                     N/A
28     WU   13.87                     6.12                     N/A
29     MU   51.85                     6.13                     N/A
30    MOS   54.89                     6.26                     N/A
31    IVZ   14.94                     6.33                     N/A
32     IP   31.71                     6.39                     N/A
33     GM   33.83                     6.43                     N/A
34    HBI    7.64                     6.43                     N/A
35    MHK   98.97                     6.50                     N/A
36    VLO  111.92                     6.55                     N/A
37    OXY   67.23                     6.58                     N/A
38    BEN   22.63                     6.72                     N/A
39   FANG  144.64                     6.80                     N/A
40    MRO   28.78                     6.97                     N/A
41    AIZ  155.89                     7.10                     N/A
42     GS  307.89                     7.10                     N/A
43    STX   54.33                     7.20                     N/A
44    KEY   16.38                     7.27                     N/A
45     VZ   38.02                     7.44                     N/A
46    WDC   34.87                     7.50                     N/A
47    UNM   41.75                     7.73                     N/A
48    PSX   91.31                     7.77                     N/A
49    MPC  108.93                     7.79                     N/A

## Calculating the Number of Shares to Buy
We now need to calculate the number of shares we need to buy. 

To do this, we will use the `portfolio_input` function that we created in our momentum project.

I have included this function below.

In [4]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input("Enter the value of your portfolio:")

    try:
        val = float(portfolio_size)
    except ValueError:
        print("That's not a number! \n Try again:")
        portfolio_size = input("Enter the value of your portfolio:")

Use the `portfolio_input` function to accept a `portfolio_size` variable from the user of this script.

In [56]:
portfolio_input()

Enter the value of your portfolio:1000

You can now use the global `portfolio_size` variable to calculate the number of shares that our strategy should purchase.

In [59]:
position_size = float(portfolio_size)/len(final_dataframe.index)

for row in final_dataframe.index:
    final_dataframe.loc[row, 'Number of Shares to Buy'] = math.floor(position_size/final_dataframe.loc[row, 'Price'])
# final_dataframe
# sum(final_dataframe['Number of Shares to Buy'])

   Ticker   Price  Price-to-Earnings Ratio Number of Shares to Buy
0     NRG   41.50                     2.98                       0
1     AIG   49.89                     3.33                       0
2     PVH   47.50                     3.59                       0
3     NUE  121.57                     3.71                       0
4       F   11.65                     4.05                       1
5     COF   96.24                     4.07                       0
6     HPE   12.30                     4.40                       1
7    DISH   14.43                     4.43                       1
8     HPQ   26.13                     4.44                       0
9     PHM   40.95                     4.46                       0
10    AIV    7.20                     4.50                       2
11    SYF   31.23                     4.58                       0
12    MGM   32.85                     4.68                       0
13    PFG   76.59                     4.75                       0
14    DHI   73.79                     4.82                       0
15    APA   42.26                     4.94                       0
16    LYB   81.03                     4.99                       0
17    DOW   46.85                     5.00                       0
18    LEN   80.77                     5.18                       0
19     CE   95.36                     5.23                       0
20    WBA   33.24                     5.33                       0
21   INTC   26.00                     5.43                       0
22    KSS   27.66                     5.43                       0
23      C   43.30                     5.44                       0
24      T   15.20                     5.61                       1
25   ZION   50.40                     5.84                       0
26    TSN   66.70                     6.00                       0
27    DFS   94.63                     6.02                       0
28     WU   13.87                     6.12                       1
29     MU   51.85                     6.13                       0
30    MOS   54.89                     6.26                       0
31    IVZ   14.94                     6.33                       1
32     IP   31.71                     6.39                       0
33     GM   33.83                     6.43                       0
34    HBI    7.64                     6.43                       2
35    MHK   98.97                     6.50                       0
36    VLO  111.92                     6.55                       0
37    OXY   67.23                     6.58                       0
38    BEN   22.63                     6.72                       0
39   FANG  144.64                     6.80                       0
40    MRO   28.78                     6.97                       0
41    AIZ  155.89                     7.10                       0
42     GS  307.89                     7.10                       0
43    STX   54.33                     7.20                       0
44    KEY   16.38                     7.27                       1
45     VZ   38.02                     7.44                       0
46    WDC   34.87                     7.50                       0
47    UNM   41.75                     7.73                       0
48    PSX   91.31                     7.77                       0
49    MPC  108.93                     7.79                       0

## Building a Better (and More Realistic) Value Strategy
Every valuation metric has certain flaws.

For example, the price-to-earnings ratio doesn't work well with stocks with negative earnings.

Similarly, stocks that buyback their own shares are difficult to value using the price-to-book ratio.

Investors typically use a `composite` basket of valuation metrics to build robust quantitative value strategies. In this section, we will filter for stocks with the lowest percentiles on the following metrics:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortization (EV/EBITDA)
* Enterprise Value divided by Gross Profit (EV/GP)

Some of these metrics aren't provided directly by the IEX Cloud API, and must be computed after pulling raw data. We'll start by calculating each data point from scratch.

In [61]:
symbol = 'AAPL'
batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol}&types=quote&token={IEX_CLOUD_API_TOKEN}'
data = requests.get(batch_api_call_url).json()

# Price-to-earnings ratio
pe_ratio = data[symbol]['quote']['peRatio']
# Price-to-book ratio
pb_ratio = np.NaN
# Price-to-sales ratio
ps_ratio = np.NaN
# Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortization (EV/EBITDA)
ev_to_ebitda = np.NaN
# Enterprise Value divided by Gross Profit (EV/GP)
ev_to_gross_profit = np.NaN

23.27

Let's move on to building our DataFrame. You'll notice that I use the abbreviation `rv` often. It stands for `robust value`, which is what we'll call this sophisticated strategy moving forward.

## Dealing With Missing Data in Our DataFrame

Our DataFrame contains some missing data because all of the metrics we require are not available through the API we're using. 

You can use pandas' `isnull` method to identify missing data:

Dealing with missing data is an important topic in data science.

There are two main approaches:

* Drop missing data from the data set (pandas' `dropna` method is useful here)
* Replace missing data with a new value (pandas' `fillna` method is useful here)

In this tutorial, we will replace missing data with the average non-`NaN` data point from that column. 

Here is the code to do this:

Now, if we run the statement from earlier to print rows that contain missing data, nothing should be returned:

## Calculating Value Percentiles

We now need to calculate value score percentiles for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* EV/EBITDA
* EV/GP

Here's how we'll do this:

## Calculating the RV Score
We'll now calculate our RV Score (which stands for Robust Value), which is the value score that we'll use to filter for stocks in this investing strategy.

The RV Score will be the arithmetic mean of the 4 percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the mean function from Python's built-in statistics module.

## Selecting the 50 Best Value StocksÂ¶

As before, we can identify the 50 best value stocks in our universe by sorting the DataFrame on the RV Score column and dropping all but the top 50 entries.

## Calculating the Number of Shares to Buy
We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a for loop to calculate the number of shares to buy for each stock in our investment universe.

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

## Creating the Formats We'll Need For Our .xlsx File
You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase
* Float formats with 1 decimal for each valuation metric

Since we already built some formats in past sections of this course, I've included them below for you. Run this code cell before proceeding.

## Saving Our Excel Output
As before, saving our Excel output is very easy: