In [120]:
import numpy as np
import pandas as pd
from datetime import date

In [121]:
today = str(date.today())

In [122]:
'america_'+today

'america_2023-08-03'

## Initial Data

In [123]:
initial_df = pd.read_csv('america_'+today+'.csv')
initial_df = initial_df.drop(columns=['Description'])
change_tracker_df = pd.DataFrame()
change_tracker_df['Ticker'] = initial_df['Ticker']
change_tracker_df['Sum_of_price_change'] = 0
change_tracker_df['Sum_of_volume_change'] = 0

divider = 1

In [124]:
initial_df

     Ticker     Price  Change %  Volume
0         A  125.4950 -1.734398  419164
1        AA   33.9900  0.176835  714395
2       AAA   24.6900  0.121654   10012
3      AAAU   19.1900  0.078227  363599
4       AAC   10.6400  0.094073   32169
...     ...       ...       ...     ...
7109   ZVSA    0.1699 -0.058824  380993
7110    ZWS   29.9400 -1.448321  218033
7111   ZYME    7.5000  2.459016   64831
7112   ZYNE    0.3510 -4.826464   96744
7113   ZYXI    8.4400  1.809409   47757

[7114 rows x 4 columns]

## Functions

In [ ]:
# def create_change_tracking_df(prev_df, new_df):
#     change_tracker = pd.DataFrame()
#     change_tracker[]

## Calculate change in volume

In [196]:
#new incoming df
new_df = pd.read_csv('america_'+today+' ('+str(divider)+')'+'.csv')
new_df = new_df.drop(columns=['Description'])

#==================================================
change_tracker_df['Sum_of_price_change'] += ((new_df['Price'] - initial_df['Price'])/initial_df['Price'])*100
change_tracker_df['Sum_of_volume_change'] += ((new_df['Volume'] - initial_df['Volume'])/initial_df['Volume'])*100
change_tracker_df['Current_price_change'] = ((new_df['Price'] - initial_df['Price'])/initial_df['Price'])*100
change_tracker_df['Current_volume_change'] = ((new_df['Volume'] - initial_df['Volume'])/initial_df['Volume'])*100
change_tracker_df['Avg_price_change'] = change_tracker_df['Sum_of_price_change'] / divider
change_tracker_df['Avg_volume_change'] = change_tracker_df['Sum_of_volume_change'] / divider
# change_tracker_df['Volume_diff'] = change_tracker_df['Current_volume_change']-change_tracker_df['Avg_volume_change']
divider += 1
initial_df = new_df
#==================================================
rel_vol_df = pd.DataFrame()
rel_vol_df['Ticker'] = new_df['Ticker']
rel_vol_df['Price'] = new_df['Price']
rel_vol_df['Price_diff'] = change_tracker_df['Current_price_change'] - change_tracker_df['Avg_price_change']
rel_vol_df['Volume_diff'] = change_tracker_df['Current_volume_change'] - change_tracker_df['Avg_volume_change']
#==================================================

# average volume change
# percentage diff from current volume and average volume change
# change_tracker_df.sort_values(by='Volume_diff', ascending=False)[:50]

In [197]:
rel_vol_df = rel_vol_df.sort_values(by='Volume_diff', ascending=False)[:50]
rel_vol_df = rel_vol_df.reset_index(drop=True)
rel_vol_df

   Ticker     Price    Price_diff   Volume_diff
0    MULN    0.1350   -435.398408  3.727669e+07
1     QQQ  374.3550   1065.170438  7.211527e+06
2     TMF    6.1201  -1190.543312  6.084598e+06
3    KWEB   30.9500   -739.462347  5.839552e+06
4    NKLA    3.4100  -2129.229534  4.290867e+06
5      PR   11.7300   -228.707182  4.239215e+06
6     POL    0.1890   -477.667214  3.410104e+06
7     NIO   15.6550  -1956.698117  2.816386e+06
8    STEM    6.8650  -2350.419176  2.501304e+06
9    QCOM  117.0400  -1272.663334  2.454426e+06
10    GLD  179.5500   -943.270084  2.032191e+06
11   TDOC   26.0400   -925.807966  1.984993e+06
12   UVXY   18.5800  -1055.171192  1.914988e+06
13      T   14.1100  -2144.384321  1.716245e+06
14   ROKU   89.7650   -768.565637  1.573698e+06
15    TGI    9.1400   -645.160669  1.543916e+06
16    KEY   11.8650   -119.239130  1.511222e+06
17   SPXS   13.5950   -937.651374  1.196242e+06
18   SPWR    9.0201   -668.695892  1.155803e+06
19    LQD  104.7700   -214.694204  1.147129e+06
20   INTC   34.7800  -2502.602575  1.114299e+06
21    VFC   18.8650   -633.610517  1.064663e+06
22   INDA   43.6500  -1090.988059  9.958937e+05
23   SQQQ   18.2277   -361.847689  9.144552e+05
24   SOXL   25.0700  -6285.689877  9.090790e+05
25     WE    0.2199   -612.177219  8.708681e+05
26     LC    7.6373  -2484.119981  8.498125e+05
27   GOEV    0.6335   -253.730731  8.473621e+05
28    RIG    8.5750   -175.184863  8.030458e+05
29     RF   20.3950   -982.901215  7.777165e+05
30   WAVD    0.4711   -928.607047  7.725917e+05
31   SPCE    3.7700   -912.213340  7.457255e+05
32   SENS    0.8499   -803.073514  7.430958e+05
33     SE   61.6600   -657.294349  7.207129e+05
34   SPLV   62.5900   -219.950990  6.053486e+05
35    HYG   74.2750   -289.917389  6.034156e+05
36   LCID    6.9250   -857.135446  5.886936e+05
37      M   15.8750 -10740.581087  5.869316e+05
38   PENN   24.9800     25.252568  5.606257e+05
39    GFS   59.7175    382.428538  5.504355e+05
40    MDB  401.2800   1106.728669  5.497107e+05
41   QUOT    3.9650   -345.072792  5.335941e+05
42   SHOP   59.2960   -404.811931  5.199117e+05
43     SQ   73.0000   -195.601256  4.881807e+05
44   TTOO    0.3903   -302.577033  4.613978e+05
45   GSAT    1.1750  -1382.225504  4.368547e+05
46     VZ   32.9800    917.961651  4.278172e+05
47   TGTX   11.2100   -261.737878  4.065460e+05
48   PSTG   37.6850   -443.911161  3.947045e+05
49    RTX   84.5050   -826.010269  3.788757e+05

In [144]:
divider

12

In [142]:
initial_df

     Ticker     Price  Change %   Volume
0         A  126.0900 -1.268499   538085
1        AA   34.2600  0.972591  1075701
2       AAA   24.6900  0.121654    10076
3      AAAU   19.1963  0.111082   472574
4       AAC   10.6400  0.094073    32443
...     ...       ...       ...      ...
7293   ZVSA    0.1674 -1.529412   436805
7294    ZWS   30.0550 -1.069783   246197
7295   ZYME    7.4200  1.366120    79441
7296   ZYNE    0.3597 -2.467462   100117
7297   ZYXI    8.5050  2.593486    59324

[7298 rows x 4 columns]

In [198]:
check = change_tracker_df[change_tracker_df['Ticker'] == 'MULN']

In [199]:
check['Current_volume_change']-check['Avg_volume_change']

4298   -3149.725775
dtype: float64

In [194]:
check = change_tracker_df['Current_volume_change']-change_tracker_df['Avg_volume_change']

In [200]:
check_df = pd.DataFrame()
check_df['Ticker'] = new_df['Ticker']
check_df['Price'] = new_df['Price']
check_df['Price_diff'] = change_tracker_df['Current_price_change'] - change_tracker_df['Avg_price_change']
check_df['Volume_diff'] = change_tracker_df['Current_volume_change'] - change_tracker_df['Avg_volume_change']

In [202]:
check = check_df[check_df['Ticker'] == 'MULN']

In [203]:
check

     Ticker  Price  Price_diff   Volume_diff
4475   MULN  0.135 -435.398408  3.727669e+07